fix: adjusting package location and scripts behavior

diff --git a/scripts/03_prepare-and-build b/scripts/03_prepare-and-build
--- a/scripts/03_prepare-and-build
+++ b/scripts/03_prepare-and-build
@@ -47,7 +47,10 @@ if [ -n "${failed}" ]; then
     for f in ${failed}; do
         echo "[PrepareAndBuild] - ${f}"
     done
-    exit 1
+    # exit 1
 fi
+
+
+echo "failed=$failed" >> "$GITHUB_OUTPUT"
 
 echo "[PrepareAndBuild] - Starting prepare and build OK"
